server:
  port: 9999

# 数据库配置
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/AEsource?currentSchema=test
    username: postgres
    password: "Yn040629."
    driver-class-name: org.postgresql.Driver

# 配置MyBatis实体和xml映射
mybatis:
  #配置xml位置
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true


